language: generic

notifications:
  email:
    recipients:
      - knutole@mapic.io
    on_success: change
    on_failure: change
  slack:
    rooms:
      - mapic-io:NKaii0z3tRkeDyXaDbRauRFp
    on_success: change
    on_failure: change

git:
  submodules: false

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.3
      sudo : required
      services: docker

env:
  DOCKER_COMPOSE_VERSION: 1.4.2
  MAPIC_TRAVIS: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://download.docker.com/mac/static/test/x86_64/docker-17.06.0-ce-rc4.tgz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then gunzip docker-17.06.0-ce-rc4.tgz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar xf docker-17.06.0-ce-rc4.tar; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd docker; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp docker /usr/local/bin/docker; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then docker version; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo rm -f /usr/local/bin/docker-compose; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > /tmp/docker-compose; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x /tmp/docker-compose; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo mv /tmp/docker-compose /usr/local/bin; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then docker-compose version; fi

install:
  - cd cli
  - grep --version
  - sudo bash mapic-cli.sh
  - mapic env
  - sudo mapic install docker

script:
  - mapic domain localhost
  - mapic install stable
  - mapic start
  # - mapic status
  - sleep 20
  - mapic stop
  # - mapic test all
