language: bash

notifications:
  slack:
    rooms:
      - mapic-io:NKaii0z3tRkeDyXaDbRauRFp

# git:
  # submodules: false

# matrix:
#   include:
#     - os: linux
#       dist: trusty
#       sudo: required

dist: trusty
sudo: required

install:
  - cd cli
  - sudo bash mapic-cli.sh
  - mapic version
  - sudo mapic travis install

script:
  - sudo mapic travis script
