language: bash

notifications:
  slack:
    rooms:
      - mapic-io:NKaii0z3tRkeDyXaDbRauRFp

dist: trusty
sudo: required

install:
  - cd cli
  - sudo bash mapic-cli.sh
  - mapic version
  # - sudo mapic travis install
  - mapic domain localhost
  # - sudo mapic configure
  - mapic ssl create
  - 

script:
  - sudo mapic travis start
