language: node_js

services:
  - docker

# sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services: docker
    - os: osx
      osx_image: xcode7.2
      services: docker

node_js:
  - 6

notifications:
  email: false
  slack: mapic-io:NKaii0z3tRkeDyXaDbRauRFp

branches:
  only:
    - master

script:
  - ./install-to-localhost.sh travis

cache:
  directories:
    - $HOME/.yarn-cache
