language: bash

notifications:
  slack:
    rooms:
      - mapic-io:NKaii0z3tRkeDyXaDbRauRFp

dist: trusty
sudo: required

install:
  - cd cli
  - sudo bash mapic-cli.sh
  - mapic version
  - sudo mapic travis install

script:
  - sudo mapic travis script
