language: generic

notifications:
  email: false
  slack: mapic-io:NKaii0z3tRkeDyXaDbRauRFp

git:
  submodules: false

sudo: required

dist: trusty

install:
  - cd cli
  - sudo bash mapic-cli.sh

script:
  - mapic 
