language: node_js

services:
  - docker

sudo: required

node_js:
  - 4

notifications:
  email: false

branches:
  only:
    - master

script:
  - ./install-to-localhost.sh travis

cache:
  directories:
    - $HOME/.yarn-cache