language: bash

notifications:
  slack:
    rooms:
      - mapic-io:NKaii0z3tRkeDyXaDbRauRFp

dist: trusty
sudo: required

install:
  - cd cli
  - sudo bash mapic-cli.sh
  - sudo mapic version
  # - sudo mapic install travis
  - sudo mapic config set MAPIC_USER_EMAIL travis@mapic.io
  - sudo mapic config set MAPIC_DOMAIN localhost
  - sudo mapic ssl create

script:
  - sudo mapic travis start
