language: generic

notifications:
  email: false
  slack: mapic-io:NKaii0z3tRkeDyXaDbRauRFp

git:
  submodules: false

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2
      sudo : required

install:
  - cd cli
  - sudo bash mapic-cli.sh

script:
  - mapic 
