language: bash

notifications:
  email:
    recipients:
      - knutole@mapic.io
    on_success: change
    on_failure: change
  slack:
    rooms:
      - mapic-io:NKaii0z3tRkeDyXaDbRauRFp
    on_success: change
    on_failure: change

git:
  submodules: false

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: required

install:
  - cd cli
  - sudo bash mapic-cli.sh
  - sudo mapic install docker

script:
  - mapic domain localhost
  - mapic install travis
  - mapic start
  - mapic logs &
  - sleep 240
  - mapic test all
  - mapic stop
