language: generic

services:
  - docker

notifications:
  email: false
  slack: mapic-io:NKaii0z3tRkeDyXaDbRauRFp

git:
  submodules: false
  depth: 1

install:
  - cd cli && bash mapic-cli.sh

script:
  - mapic 
