language: node_js

services:
  - docker

sudo: required

node_js:
  - 6

notifications:
  email: false

branches:
  only:
    - master

script:
  - ./ci.sh

cache:
  directories:
    - $HOME/.yarn-cache
