language: bash

notifications:
  email:
    recipients:
      - knutole@mapic.io
    on_success: change
    on_failure: change
  slack:
    rooms:
      - mapic-io:NKaii0z3tRkeDyXaDbRauRFp
    on_success: change
    on_failure: change

git:
  submodules: false

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: required

install:
  - cd cli
  - sudo bash mapic-cli.sh
  - sudo mapic install docker
  - mapic version
  # - sudo touch /etc/docker/daemon.json
  - docker version
  # - sudo echo '{"experimental":true}' >> daemon.json
  # - sudo cp daemon.json /etc/docker/daemon.json
  # - sudo systemctl restart docker
  - sudo echo 'DOCKER_OPTS="--experimental=true"' >> tmp-docker
  - sudo cp -f tmp-docker /etc/default/docker
  - sudo service docker restart
  - docker version
  - docker swarm init

script:
  - mapic domain localhost
  - mapic install travis
  - mapic start
  - mapic status
  - mapic logs
  - sleep 240
  - mapic status
  - mapic test all
  - mapic stop
  # - mapic logs 
