language: generic

services:
  - docker

notifications:
  email: false
  slack: mapic-io:NKaii0z3tRkeDyXaDbRauRFp

git:
  submodules: false

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: xenial
      sudo: required
    - os: linux
      dist: precise
      sudo: required
    - os: linux
      dist: zesty
      sudo: required
    - os: linux
      dist: yakkety
      sudo: required
    - os: linux
      dist: artful
      sudo: required
    - os: osx
      osx_image: xcode7.3.1
      sudo : required
    - os: osx
      osx_image: xcode8.3
      sudo : required

install:
  - cd cli
  - sudo bash mapic-cli.sh
  - mapic install docker

script:
  - mapic domain localhost
  - mapic install stable
  - mapic start
  - mapic status
  # - sleep 20
  # - mapic test all
