language: generic

notifications:
  email:
    recipients:
      - knutole@mapic.io
    on_success: change
    on_failure: change
  slack:
    rooms:
      - mapic-io:NKaii0z3tRkeDyXaDbRauRFp
    on_success: change
    on_failure: change

git:
  submodules: false

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: required
    # - os: osx
    #   osx_image: xcode8.3
    #   sudo : required
    #   services: docker
    #   language: ruby

env:
  DOCKER_COMPOSE_VERSION: 1.4.2
  MAPIC_TRAVIS: true

# before_install:
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ; fi

install:
  - cd cli
  - grep --version
  - sudo bash mapic-cli.sh
  - mapic env
  - sudo mapic install docker

script:
  - mapic domain localhost
  - mapic install stable
  - mapic start
  - mapic logs &
  # - mapic status
  - sleep 20
  - mapic stop
  # - mapic test all
