language: generic

notifications:
  email:
    recipients:
      - knutole@mapic.io
    on_success: change
    on_failure: change
  slack:
    rooms:
      - mapic-io:NKaii0z3tRkeDyXaDbRauRFp
    on_success: change
    on_failure: change

git:
  submodules: false

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: required

install:
  - cd cli
  - grep --version
  - sudo bash mapic-cli.sh
  - mapic env
  - sudo mapic install docker

script:
  - mapic domain localhost
  - mapic install stable
  - mapic start
  - mapic logs &
  - sleep 240
  - mapic test mile
  - mapic test engine
  # - mapic test mapicjs
  # - mapic test all
  - mapic stop
