language: generic

services:
  - docker

notifications:
  email: false
  slack: mapic-io:NKaii0z3tRkeDyXaDbRauRFp

git:
  submodules: false

install:
  - cd cli 
  - ls -l
  - bash mapic-cli.sh

script:
  - mapic 
