# see domain-specific .yml for documentation
engine:
  # image: mapic/geo:latest 
  image: mapic/engine:latest 
  environment:
    MAPIC_DOMAIN: ${MAPIC_DOMAIN}
  working_dir: /mapic/engine 
  restart: "no"
  expose:
    - "3001"
  volumes:
    - ${MAPIC_CONFIG_FOLDER}:/mapic/config
    - ${MAPIC_ROOT_FOLDER}/engine:/mapic/engine
    - ${MAPIC_ROOT_FOLDER}/mapic.js:/mapic/mapic.js
  command: ./start-server.sh

mile: 
  # image: mapic/geo:latest
  image: mapic/mile:latest
  environment:
    MAPIC_DOMAIN: ${MAPIC_DOMAIN}
  working_dir: /mapic/modules/mile 
  expose:
    - "3003"
  volumes:
    - ${MAPIC_CONFIG_FOLDER}:/mapic/config
    - ${MAPIC_ROOT_FOLDER}/mile:/mapic/modules/mile
  command: ./start-server.sh

nginx:
  image: mapic/nginx:latest
  volumes:
    - ${MAPIC_CONFIG_FOLDER}:/mapic/config

redis:
  image: mapic/redis:latest
  volumes:
    - ${MAPIC_CONFIG_FOLDER}:/mapic/config

mongo: 
  image: mapic/mongo:latest
  volumes:
    - ${MAPIC_CONFIG_FOLDER}:/mapic/config

postgis:
  image: mapic/postgis:latest
  volumes:
    - ${MAPIC_CONFIG_FOLDER}:/mapic/config
