version: '3'
volumes: 
  mapic_data_store_localhost:
  mongo_store_localhost:
  postgis_store_localhost:
  redis_layers_store_localhost:
  redis_stats_store_localhost:
  redis_tokens_store_localhost:

networks:
  mapic:

services:
  engine:
    image: mapic/geo:latest 
    environment:
      MAPIC_DOMAIN: ${MAPIC_DOMAIN}
      MAPIC_PRODMODE: 'false'
    working_dir: /mapic/engine 
    command: ./start-server.sh
    volumes:
      - ${MAPIC_CONFIG_FOLDER}:/mapic/config
      - ${MAPIC_ROOT_FOLDER}/engine:/mapic/engine
      - ${MAPIC_ROOT_FOLDER}/mapic.js:/mapic/mapic.js
      - mapic_data_store_localhost:/data
    networks:
      mapic:
        aliases:
          - engine.docker
    # links:
    #   - mongo
    #   - redislayers
    #   - redisstats
    #   - redistemp
    #   - redistokens
    #   - postgis
    

  mile: 
    image: mapic/geo:latest
    environment:
      MAPIC_DOMAIN: ${MAPIC_DOMAIN}
      MAPIC_PRODMODE: 'false'
    working_dir: /mapic/mile 
    command: ./start-server.sh

    # expose:
      # - "3001"
    volumes:
      - ${MAPIC_CONFIG_FOLDER}:/mapic/config
      - ${MAPIC_ROOT_FOLDER}/mile:/mapic/mile
      - mapic_data_store_localhost:/data
    networks:
      mapic:
        aliases:
          - mile.docker
    # links: 
    #   - engine 
    #   - redislayers
    #   - redisstats
    #   - redistokens
    #   - redistemp
    #   - postgis
    
  
  nginx:
    image: mapic/nginx:latest
    volumes:
      - ${MAPIC_CONFIG_FOLDER}:/mapic/config
    ports:
      - 443:443
      - 80:80
    networks:
      mapic:
        aliases:
          - nginx.docker

  redislayers:
    image: redis:latest
    volumes:
      - ${MAPIC_CONFIG_FOLDER}:/mapic/config
      # - ../../../config/${MAPIC_DOMAIN}:/mapic/config
      - redis_layers_store_localhost:/data
    command: "redis-server /mapic/config/redis.layers.conf"
    networks:
      mapic:
        aliases:
          - redislayers.docker

  redisstats:
    image: redis:latest
    volumes:
      - ${MAPIC_CONFIG_FOLDER}:/mapic/config
      # - ../../../config/${MAPIC_DOMAIN}:/mapic/config
      - redis_stats_store_localhost:/data
    command: "redis-server /mapic/config/redis.stats.conf"
    networks:
      mapic:
        aliases:
          - redisstats.docker

  redistokens:
    image: redis:latest
    volumes:
      - ${MAPIC_CONFIG_FOLDER}:/mapic/config
      # - ../../../config/${MAPIC_DOMAIN}:/mapic/config
      - redis_tokens_store_localhost:/data
    command: "redis-server /mapic/config/redis.tokens.conf"
    networks:
      mapic:
        aliases:
          - redistokens.docker

  redistemp:
    image: redis:latest
    volumes:
      - ${MAPIC_CONFIG_FOLDER}:/mapic/config
      # - ../../../config/${MAPIC_DOMAIN}:/mapic/config
    command: "redis-server /mapic/config/redis.temp.conf"
    networks:
      mapic:
        aliases:
          - redistemp.docker

  mongo: 
    image: mapic/mongo:latest
    volumes:
      - ${MAPIC_CONFIG_FOLDER}:/mapic/config
      # - ../../../config/${MAPIC_DOMAIN}:/mapic/config
      - mongo_store_localhost:/data/db
    networks:
      mapic:
        aliases:
          - mongo.docker

  postgis:
    image: mapic/postgis:latest
    volumes:
      - ${MAPIC_CONFIG_FOLDER}:/mapic/config
      # - ../../../config/${MAPIC_DOMAIN}:/mapic/config
      - postgis_store_localhost:/var/lib/postgresql
    networks:
      mapic:
        aliases:
          - postgis.docker