# see domain-specific .yml for documentation
engine:
  image: mapic/engine:latest 
  environment:
    MAPIC_DOMAIN: ${MAPIC_DOMAIN}
  working_dir: /mapic/modules/engine 
  volumes:
    - ${MAPIC_ROOT_FOLDER}/config/${MAPIC_DOMAIN}:/mapic/config
    - ${MAPIC_ROOT_FOLDER}/modules:/mapic/modules

mile: 
  image: mapic/mile:latest
  environment:
    MAPIC_DOMAIN: ${MAPIC_DOMAIN}
  working_dir: /mapic/modules/mile 
  volumes:
    - ${MAPIC_ROOT_FOLDER}/config/${MAPIC_DOMAIN}:/mapic/config
    - ${MAPIC_ROOT_FOLDER}/modules:/mapic/modules

nginx:
  image: mapic/nginx:latest
  volumes:
    - ${MAPIC_ROOT_FOLDER}/config/${MAPIC_DOMAIN}:/mapic/config

redis:
  image: redis:latest
  volumes:
    - ${MAPIC_ROOT_FOLDER}/config/${MAPIC_DOMAIN}:/mapic/config

mongo: 
  image: mapic/mongo:latest
  volumes:
    - ${MAPIC_ROOT_FOLDER}/config/${MAPIC_DOMAIN}:/mapic/config

postgis:
  image: mapic/postgis:latest
  volumes:
    - ${MAPIC_ROOT_FOLDER}/config/${MAPIC_DOMAIN}:/mapic/config
