engine:
  extends:
    file: common.yml
    service: engine
  links:
    - mongo
    - redislayers
    - redisstats
    - redistemp
    - redistokens
    - postgis
  environment:
    MAPIC_PRODMODE: 'false'
  volumes_from:
    - data_store_globesar

mile: 
  extends:
    file: common.yml
    service: mile
  links: 
    - engine 
    - redislayers
    - redisstats
    - redistokens
    - redistemp
    - postgis
  environment:
    MAPIC_PRODMODE: 'false'
  volumes_from:
    - data_store_globesar
  
nginx:
  extends:
    file: common.yml
    service: nginx
  ports:
    - 443:443
    - 80:80
  links: 
    - mile
    - engine

redislayers:
  extends:
    file: common.yml
    service: redis
  volumes_from:
    - redis_store_globesar
  command: "redis-server /mapic/config/redis.layers.conf"

redisstats:
  extends:
    file: common.yml
    service: redis
  volumes_from:
    - redis_stats_store_globesar
  command: "redis-server /mapic/config/redis.stats.conf"

redistokens:
  extends:
    file: common.yml
    service: redis
  volumes_from:
    - store_globesar_redis_tokens
  command: "redis-server /mapic/config/redis.tokens.conf"

redistemp:
  extends:
    file: common.yml
    service: redis
  command: "redis-server /mapic/config/redis.temp.conf"

mongo: 
  extends:
    file: common.yml
    service: mongo
  volumes_from:
    - mongo_store_globesar

postgis:
  extends:
    file: common.yml
    service: postgis
  image: systemapic/postgis:latest
  volumes_from:
    - postgis_store_globesar
  volumes:
    - ../../../config/${MAPIC_DOMAIN}:/systemapic/config

