## latest updated, before connection issues

version: '3'
volumes: 
  mapic_data_store_localhost:
  mongo_store_localhost:
  postgis_store_localhost:
  redis_layers_store_localhost:
  redis_stats_store_localhost:
  redis_tokens_store_localhost:

networks:
  mapic:

services:

  nginx:
    image: mapic/nginx:latest
    env_file:
      - $MAPIC_ENV_FILE
    volumes:
      - ${MAPIC_CONFIG_FOLDER}/privkey.key:/mapic/privkey.key
      - ${MAPIC_CONFIG_FOLDER}/fullchain.pem:/mapic/fullchain.pem
      - ${MAPIC_CONFIG_FOLDER}/dhparams.pem:/mapic/dhparams.pem
    deploy:
      placement:
        constraints: 
        - node.ip == $MAPIC_IP
    depends_on:
      - mile
      - engine
    ports:
      - 443:443
      - 80:80
    networks:
      mapic:
        aliases:
          - nginx.docker

  engine:
    image: mapic/geo:latest 
    env_file:
      - $MAPIC_ENV_FILE
    deploy:
      placement:
        constraints: 
          - node.ip == $MAPIC_IP
    working_dir: /mapic/engine 
    command: ./start-server.sh
    volumes:
      - ${MAPIC_ROOT_FOLDER}:/mapic
      - mapic_data_store_localhost:/data
    networks:
      mapic:
        aliases:
          - engine.docker

  mile: 
    image: mapic/geo:latest
    env_file:
      - $MAPIC_ENV_FILE
    deploy:
      replicas: 1
      placement:
        constraints: 
          # - node.ip == $MAPIC_IP
          - node.ip != $MAPIC_IP
    working_dir: /mapic/mile 
    command: ./start-server.sh
    volumes:
      - ${MAPIC_ROOT_FOLDER}:/mapic
      - mapic_data_store_localhost:/data
    networks:
      mapic:
        aliases:
          - mile.docker
 
  redis:
    image: mapic/redis:latest
    env_file:
      - $MAPIC_ENV_FILE
    volumes:
      - redis_layers_store_localhost:/data
    deploy:
      replicas: 1
      placement:
        constraints: 
          - node.ip == $MAPIC_IP
    networks:
      mapic:
        aliases:
          - redis.docker

  mongo: 
    image: mapic/mongo:latest
    env_file:
      - $MAPIC_ENV_FILE
    volumes:
      - mongo_store_localhost:/data/db
    deploy:
      placement:
        constraints: 
          - node.ip == $MAPIC_IP
    networks:
      mapic:
        aliases:
          - mongo.docker

  postgis:
    image: mapic/postgis:latest
    env_file:
      - $MAPIC_ENV_FILE
    volumes:
      - ${MAPIC_CONFIG_FOLDER}:/mapic/config
      - postgis_store_localhost:/var/lib/postgresql
    deploy:
      placement:
        constraints: 
          - node.ip == $MAPIC_IP
      # resources:
      #   limits:
      #     cpus: '0.9'
    networks:
      mapic:
        aliases:
          - postgis.docker
  